stages:
  - vet
  - test
  - build

.ci-tools: &ci-tools
  image: grauwoelfchen/rust-ci-tools:nightly
  except:
    - tags

# stages
format:
  stage: vet
  <<: *ci-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
  script:
    - mkdir -p .git/hooks
    - make vet:format

lint:
  stage: vet
  <<: *ci-tools
  before_script:
    - rustc --version
    - cargo --version
    - cargo clippy --version
  script:
    - mkdir -p .git/hooks
    - make vet:lint

test:
  stage: test
  <<: *ci-tools
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
    - make test:all

coverage:
  stage: test
  <<: *ci-tools
  variables:
    - KCOV_PATH: kcov
  before_script:
    - rustc --version
    - cargo --version
    - kcov --version
  script:
    - mkdir -p .git/hooks
   - cargo clean --target-dir target/debug
    - make coverage
  after_script:
    - cat target/coverage/index.json

build:
  stage: build
  image: grauwoelfchen/rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - mkdir -p .git/hooks
    - make build
  cache:
    untracked: true
